name: 'Update iOS version Info.plist'
description: 'Update the Info.plist file'
author: 'damienaicheh'
inputs:
  info-plist-path:
    description: 'Relative path for the Info.plist file.'
    required: true
  bundle-short-version-string:
    description: 'CF Bundle Short Version String'
    required: false
  bundle-version:
    description: 'CF Bundle Version'
    required: true
  app-id:
    description: 'App id'
    required: false
  bundle-display-name:
    description: 'Bundle display name'
    required: false
  print-file:
    description: 'Output the Info.plist file in console'
    required: false
  bundle-url-types:
    description: 'App scheme'
    required: false
  branch-key-live:
    description: 'Branch key'
    required: false
  branch-key-test: 
    description: 'Branch test key'
    required: false
  branch-universal-link-domains:
    description: 'Branch universal link subdomain'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file'
  color: 'blue'
